import SeasonTeam from "#/data/static/SeasonTeam";
import {
    Arsenal,
    AstonVilla,
    Bournemouth,
    Brentford,
    Brighton,
    Burnley,
    Chelsea,
    CrystalPalace,
    Everton,
    Fulham,
    LeedsUnited,
    Liverpool,
    ManchesterCity,
    ManchesterUnited,
    NewcastleUnited,
    NottinghamForest,
    Sunderland,
    TottenhamHotspur,
    WestHamUnited,
    Wolverhampton
} from "#/data/static/teams";

export const PrimerLeague25_26LiveData: SeasonTeam[] = [
    SeasonTeam.create(Arsenal, 0, 0, 0, 0, 0),
    SeasonTeam.create(AstonVilla, 0, 0, 0, 0, 0),
    SeasonTeam.create(Bournemouth, 0, 0, 0, 0, 0),
    SeasonTeam.create(Brentford, 0, 0, 0, 0, 0),
    SeasonTeam.create(Brighton, 0, 0, 0, 0, 0),
    SeasonTeam.create(Burnley, 0, 0, 0, 0, 0),
    SeasonTeam.create(Chelsea, 0, 0, 0, 0, 0),
    SeasonTeam.create(CrystalPalace, 0, 0, 0, 0, 0),
    SeasonTeam.create(Everton, 0, 0, 0, 0, 0),
    SeasonTeam.create(Fulham, 0, 0, 0, 0, 0),
    SeasonTeam.create(LeedsUnited, 0, 0, 0, 0, 0),
    SeasonTeam.create(Liverpool, 0, 0, 0, 0, 0),
    SeasonTeam.create(ManchesterCity, 0, 0, 0, 0, 0),
    SeasonTeam.create(ManchesterUnited, 0, 0, 0, 0, 0),
    SeasonTeam.create(NewcastleUnited, 0, 0, 0, 0, 0),
    SeasonTeam.create(NottinghamForest, 0, 0, 0, 0, 0),
    SeasonTeam.create(Sunderland, 0, 0, 0, 0, 0),
    SeasonTeam.create(TottenhamHotspur, 0, 0, 0, 0, 0),
    SeasonTeam.create(WestHamUnited, 0, 0, 0, 0, 0),
    SeasonTeam.create(Wolverhampton, 0, 0, 0, 0, 0)]