import SeasonTeam from "../../../../../data/static/SeasonTeam";
import {
    Ajax,
    Arsenal,
    Atalanta,
    AthleticBilbao,
    AtleticoMadrid,
    Barcelona,
    BayerLeverkusen,
    BayernMunich,
    BorussiaDortmund,
    Chelsea,
    EintrachtFrankfurt,
    Galatasaray,
    InterMilan,
    Juventus,
    Liverpool,
    ManchesterCity,
    Marseille,
    Monaco,
    Napoli,
    NewcastleUnited,
    Olympiacos,
    ParisSG,
    PSV,
    RealMadrid,
    SlaviaPrague,
    SportingCP,
    Tottenham,
    UnionSG,
    Villarreal
} from "../../../../../data/static/Teams";

export const ChampionsLeague25_26LiveData: SeasonTeam[] = [
    SeasonTeam.create(Ajax, 0, 0, 0, 0, 0),
    SeasonTeam.create(Arsenal, 0, 0, 0, 0, 0),
    SeasonTeam.create(Atalanta, 0, 0, 0, 0, 0),
    SeasonTeam.create(AthleticBilbao, 0, 0, 0, 0, 0),
    SeasonTeam.create(AtleticoMadrid, 0, 0, 0, 0, 0),
    SeasonTeam.create(Barcelona, 0, 0, 0, 0, 0),
    SeasonTeam.create(BayernMunich, 0, 0, 0, 0, 0),
    SeasonTeam.create(BayerLeverkusen, 0, 0, 0, 0, 0),
    SeasonTeam.create(BorussiaDortmund, 0, 0, 0, 0, 0),
    SeasonTeam.create(Chelsea, 0, 0, 0, 0, 0),
    SeasonTeam.create(EintrachtFrankfurt, 0, 0, 0, 0, 0),
    SeasonTeam.create(Galatasaray, 0, 0, 0, 0, 0),
    SeasonTeam.create(InterMilan, 0, 0, 0, 0, 0),
    SeasonTeam.create(Juventus, 0, 0, 0, 0, 0),
    SeasonTeam.create(Liverpool, 0, 0, 0, 0, 0),
    SeasonTeam.create(ManchesterCity, 0, 0, 0, 0, 0),
    SeasonTeam.create(Marseille, 0, 0, 0, 0, 0),
    SeasonTeam.create(Monaco, 0, 0, 0, 0, 0),
    SeasonTeam.create(Napoli, 0, 0, 0, 0, 0),
    SeasonTeam.create(NewcastleUnited, 0, 0, 0, 0, 0),
    SeasonTeam.create(Olympiacos, 0, 0, 0, 0, 0),
    SeasonTeam.create(ParisSG, 0, 0, 0, 0, 0),
    SeasonTeam.create(PSV, 0, 0, 0, 0, 0),
    SeasonTeam.create(RealMadrid, 0, 0, 0, 0, 0),
    SeasonTeam.create(SlaviaPrague, 0, 0, 0, 0, 0),
    SeasonTeam.create(SportingCP, 0, 0, 0, 0, 0),
    SeasonTeam.create(Tottenham, 0, 0, 0, 0, 0),
    SeasonTeam.create(UnionSG, 0, 0, 0, 0, 0),
    SeasonTeam.create(Villarreal, 0, 0, 0, 0, 0)
];
