// 'use client'
import "./globals.css";
import {Metadata} from "next";
import {cookies} from "next/headers";
import {LocaleCode} from "@/lib/i18n/config";
import {getDirection, isInLocales} from "@/lib/i18n/LocaleConfig";
import {LocaleProvider} from "@/providers";
import InitStaticTranslationsProvider from "@/providers/InitStaticTranslationsProvider";
import NavigationOption from "@/data/navbar/NavigationOption";
import Image from "next/image";
import React from "react";
import RootLayoutClient from "@/app/RootLayoutClient";

export const metadata: Metadata = {
    title: "My own Phoenix",
    description: "Generated by create next app",
};

export default async function RootLayout({children}: { children: React.ReactNode }) {
    const cookieStore = await cookies()
    const localeCookie = cookieStore.get('locale')?.value as LocaleCode | undefined
    const locale = localeCookie && isInLocales(localeCookie as LocaleCode)
        ? (localeCookie as LocaleCode)
        : LocaleCode.EN
    const direction = getDirection(locale)
    return (
        <html lang={locale} dir={direction.asString} className="h-full">
            <body className=" min-h-screen h-full bg-gray-100 text-gray-900">
                <LocaleProvider initialLocale={locale}>
                    <InitStaticTranslationsProvider/>
                    <RootLayoutClient>
                        {/*<div*/}
                        {/*    className="bg-gradient-to-br from-[#1e1e2f] via-[#2e2e4d] to-[#1e1e2f] text-white">*/}
                            {children}
                        {/*</div>*/}
                    </RootLayoutClient>
                    {/*<RootLayoutClient>*/}
                    {/*    /!*<div className="min-h-screen flex flex-col bg-gradient-to-br from-[#1e1e2f] via-[#2e2e4d] to-[#1e1e2f] text-white">*!/*/}
                    {/*        {children}*/}
                    {/*    /!*</div>*!/*/}
                    {/*</RootLayoutClient>*/}
                </LocaleProvider>
            </body>
        </html>
    )
}